version: '3.5'

services:
  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    volumes: 
        - ./frontend:/usr/src/app
        - /usr/src/app/node_modules
    networks:
        pubconnect-network:
            aliases: 
                - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules/
    ports: 
      - 5000:5000
    networks:
        pubconnect-network:
            aliases: 
                - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'pfeffa'
      MYSQL_PASSWORD: 'goawayyouevilhackeryou'
      MYSQL_ROOT_PASSWORD: 'goawayyouevilhackeryou'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
        pubconnect-network:
            aliases: 
                - db

  adminer:
    image: adminer
    restart: always
    networks:
        pubconnect-network:
            aliases: 
                - adminer
  
  nginx-proxy:
    depends_on:
        - frontend
        - backend
        - adminer
        - db
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - 80:80
    networks:
        pubconnect-network:
            aliases: 
                - nginx-proxy

networks:
    pubconnect-network: