version: '2.1'

services: 
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

  # backend:
  #   restart: always
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   volumes: 
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules/
  #   ports: 
  #     - 5000:5000
  #   depends_on: 
  #     db:
  #       condition: service_healthy
  #   links:
  #     - db