version: '3.8'

services: 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pc-backend
    networks:
      - pubconnect-net
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules/
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: pc-db
    networks:
      - pubconnect-net
    env_file: ./pubconnect.env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_HOST_VOLUME:-./dbdata}:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: pc-adminer
    networks:
      - pubconnect-net
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pc-frontend
    networks:
      - pubconnect-net
    volumes: 
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  nginx:
    image: library/nginx:1
    container_name: pc-nginx
    networks:
      - pubconnect-net
    env_file: ./pubconnect.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_HOST_CONFIG_DIR:-./nginx}/default.conf:/etc/nginx/conf.d/default.conf
      - ${NGINX_HOST_CONFIG_DIR:-./nginx}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_HOST_SSL_DIR:-./ssl}:/etc/ssl
    restart: unless-stopped

networks:
  pubconnect-net:
    ipam:
      driver: default
      config:
        - subnet: "10.100.1.0/24"